name: yoni schaffer
favicon: null
layout_spectrum: 0.13081119651906192
typography_spectrum: 0.32860225974582136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6583339041098952
  lightness: 0.6936772814951837
  saturation: 0.9529617393855006
  rhythmicContrast: 0.008309801341965795
purpose: []
