name: yoni schaffer
favicon: null
layout_spectrum: 0.13081119651906192
typography_spectrum: 0.32860225974582136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#93795e'
    - '#ead8d1'
    - '#664030'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
